### ISSUE TITLE
Support for symlinked shared virtualenv instead of per-deploy build.

### ISSUE THREAD

**Issue by pobocks** [mattjmorrison/capistrano-django#9]
Currently, this script builds a new virtualenv per deploy, which extends deploy times by quite a bit.

I've written some code to build the virtualenv once, in the shared directory, and then symlink it into the release directory.  I'm submitting a pull request - AFAICT, it doesn't break anything, and is switchable via one config variable.

**Comment by mattjmorrison** [comment]
This is fixed in version 3.1.
